theme: readthedocs
site_name: Django Semantic UI admin theme
nav:
  - Home: index.md
  - Install: install.md
  - Customization: customization.md
  - Awesome optional features: awesome.md
  - Screenshots: screenshots.md
  - Contributing: contributing.md
  - Notes: notes.md
  - Changes: changes.md
